# -*- coding: utf-8 -*-
"""ControlNet_Latent_Walk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCwJWXy3OmGx3Fj-9wdpUmiH2LstL3lh
"""

# After trying to create a latent walk from the following references
# 1. Outpainting I - Controlnet version. Url: https://huggingface.co/blog/OzzyGT/outpainting-controlnet
# 2. A walk through latent space with Stable Diffusion. Url: https://keras.io/examples/generative/random_walks_with_stable_diffusion/

# I created a 'latent' walk based on code from ChatGPT
# 3. ChatGPT log Url: https://chatgpt.com/share/6a31c842-dec4-83eb-9b89-150aed089c89
# 4: ChatGPT https://chatgpt.com/share/6a17139b-3688-83eb-be26-68790e67b334

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Correct directory path for project
### cd error: https://chatgpt.com/share/6a31a9ad-4c68-83ed-939b-93ad436f48b8
# %cd /content/drive/MyDrive/2026/EMI/outpaint-hug

# Import necessary libraries
# 1:
import random
from io import BytesIO

import requests
import torch
from PIL import Image

from diffusers import (
    AutoPipelineForImage2Image,
    ControlNetModel,
    DPMSolverMultistepScheduler,
    StableDiffusionXLControlNetPipeline,
)
from diffusers.image_processor import IPAdapterMaskProcessor
from diffusers.utils import load_image, logging
from diffusers.utils.logging import set_verbosity

# 1: Controlnet Model
### 1: "controlnet for SDXL trained for inpainting by destitech"
controlnet = ControlNetModel.from_pretrained(
    "destitech/controlnet-inpaint-dreamer-sdxl", torch_dtype=torch.float16, variant="fp16"
)

# 1:
pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
    "RunDiffusion/Juggernaut-XL-v9",
    torch_dtype=torch.float16,
    variant="fp16",
    controlnet=controlnet,
).to("cuda")

### 1: "[Controlnet Model is] easy to use, you just need to paint white the parts you want to replace"
### 1: "what I'm going to do is paint white the transparent part of the image.""

# 1: To paint white the alpha channel of an image I use this code"
### Fetches an image with an edited transparent area illustrating what needs to be inpainted

# 4: Previously used code from a different project
input_folder = '/content/drive/MyDrive/2026/EMI/outpaint-hug/Hockney-Collage-Pieces'

pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
pipeline.scheduler.config.use_karras_sigmas = True

# adding ip adapter
pipeline.load_ip_adapter(
    "h94/IP-Adapter",
    subfolder="sdxl_models",
    weight_name="ip-adapter-plus_sdxl_vit-h.safetensors",
    image_encoder_folder="models/image_encoder",
)
pipeline.set_ip_adapter_scale(0.8)

collage_image = Image.open(f'{input_folder}/collage_cutout_original_image.png')
ip_collage_image = collage_image

mask = Image.open(f'{input_folder}/full_image_2.png')
ip_mask = mask

processor = IPAdapterMaskProcessor()
ip_masks = processor.preprocess(ip_mask, height=1024, width=1024)

response = ip_collage_image

control_image = collage_image
new_controlnet_image = Image.new("RGBA", control_image.size, "WHITE")
new_controlnet_image.alpha_composite(control_image)

### 1: "This image has a 720x720 px size, SDXL works better with 1024x1024 images,
###     so the generations will be upscaled
###     you can use the smaller image but you'll probably get a lower quality image."

### "The conditional scale affects how much of the original image will be preserved,
###  since this is an outpaint, it's safe to use higher values,
###. for inpainting and complex images is better to use lower values around 0.5

# 1: Prompts
prompt = "High quality"
negative_prompt = ""

# 1:
seed = random.randint(0, 2**32 - 1)
generator = torch.Generator(device="cpu").manual_seed(seed)

# 3:

seed1 = 1234
seed2 = 5678

g1 = torch.Generator("cpu").manual_seed(seed1)
g2 = torch.Generator("cpu").manual_seed(seed2)

latent1 = pipeline(
    prompt=prompt,
    negative_prompt=negative_prompt,
    height=1024,
    width=1024,
    guidance_scale=6.5,
    num_inference_steps=25,
    image=new_controlnet_image,
    controlnet_conditioning_scale=0.2, # lower for more ip influence
    control_guidance_end=0.2,
    generator=g1,
    ip_adapter_image=ip_collage_image,
    cross_attention_kwargs={"ip_adapter_masks": ip_masks},
    output_type="latent",
).images[0]

latent2 = pipeline(
    prompt=prompt,
    negative_prompt=negative_prompt,
    height=1024,
    width=1024,
    guidance_scale=6.5,
    num_inference_steps=25,
    image=new_controlnet_image,
    controlnet_conditioning_scale=0.2, # lower fore mor ip influence
    control_guidance_end=0.2,
    generator=g2,
    ip_adapter_image=ip_collage_image,
    cross_attention_kwargs={"ip_adapter_masks": ip_masks},
    output_type="latent",
).images[0]

pipeline_img2img = AutoPipelineForImage2Image.from_pipe(pipeline, controlnet=None)

prompt = "High quality"

# 3:
def lerp(a, b, t):
    return (1 - t) * a + t * b

# 3:

frames = []

for i in range(3):
    t = i / 59

    latents = lerp(latent1, latent2, t)

    image = pipeline_img2img(
        prompt=prompt,
        negative_prompt=negative_prompt,
        height=1024,
        width=1024,
        guidance_scale=3.0, # higher for stronger prompt reference
        num_inference_steps=25,
        generator=generator,
        image=latents,
        strength=0.9, # higher = model more freedom to incorporate the reference image
        ip_adapter_image=ip_mask,
        cross_attention_kwargs={"ip_adapter_masks": ip_masks},
    ).images[0]

    frames.append(image)

from PIL import Image

# frames = [PIL.Image, PIL.Image, ...]

frames[0].save(
    "biscuit_18.gif",
    save_all=True,
    append_images=frames[1:],
    duration=250,  # milliseconds per frame
    loop=0,        # 0 = infinite loop
)

from IPython.display import Image as IImage
IImage("biscuit_18.gif", width=300)