# -*- coding: utf-8 -*-
"""Latent-Hockney-Thu-25-June.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIQWcu8WfHY04GMyoL0BHKiNQ0eTajcG
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/2026/EMI/outpaint-hug

# After trying to create a latent walk from the following references
# 1. Outpainting I - Controlnet version. Url: https://huggingface.co/blog/OzzyGT/outpainting-controlnet
# 2. A walk through latent space with Stable Diffusion. Url: https://keras.io/examples/generative/random_walks_with_stable_diffusion/

# I created a 'latent' walk based on code from ChatGPT
# 3. ChatGPT log Url: https://chatgpt.com/share/6a31c842-dec4-83eb-9b89-150aed089c89
# 4: ChatGPT https://chatgpt.com/share/6a17139b-3688-83eb-be26-68790e67b334

# Import necessary libraries
# 1:
import random
from io import BytesIO

import requests
import torch
from PIL import Image

from diffusers import (
    AutoPipelineForImage2Image,
    ControlNetModel,
    DPMSolverMultistepScheduler,
    StableDiffusionXLControlNetPipeline,
)
from diffusers.image_processor import IPAdapterMaskProcessor
from diffusers.utils import load_image, logging
from diffusers.utils.logging import set_verbosity

# 1: Controlnet Model
### 1: "controlnet for SDXL trained for inpainting by destitech"
controlnet = ControlNetModel.from_pretrained(
    "destitech/controlnet-inpaint-dreamer-sdxl", torch_dtype=torch.float16, variant="fp16"
)

# 1:
pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
    "RunDiffusion/Juggernaut-XL-v9",
    torch_dtype=torch.float16,
    variant="fp16",
    controlnet=controlnet,
).to("cuda")

## 1: "[Controlnet Model is] easy to use, you just need to paint white the parts you want to replace"
### 1: "what I'm going to do is paint white the transparent part of the image.""

# 1: To paint white the alpha channel of an image I use this code"
### Fetches an image with an edited transparent area illustrating what needs to be inpainted

# 4: Previously used code from a different project
input_folder = '/content/drive/MyDrive/2026/EMI/outpaint-hug/Hockney-Collage-Pieces'

pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
pipeline.scheduler.config.use_karras_sigmas = True

# adding ip adapter
pipeline.load_ip_adapter(
    "h94/IP-Adapter",
    subfolder="sdxl_models",
    weight_name="ip-adapter-plus_sdxl_vit-h.safetensors",
    image_encoder_folder="models/image_encoder",
)
pipeline.set_ip_adapter_scale(0.9)

collage_image = Image.open(f'{input_folder}/collage_cutout_original_image.png')
ip_collage_image = collage_image

mask = Image.open(f'{input_folder}/full_image_2.png')
ip_mask = mask

processor = IPAdapterMaskProcessor()
ip_masks = processor.preprocess(ip_mask, height=1024, width=1024)

control_image = collage_image
new_controlnet_image = Image.new("RGBA", control_image.size, "WHITE")
new_controlnet_image.alpha_composite(control_image)

### 1: "This image has a 720x720 px size, SDXL works better with 1024x1024 images,
###     so the generations will be upscaled
###     you can use the smaller image but you'll probably get a lower quality image."

### "The conditional scale affects how much of the original image will be preserved,
###  since this is an outpaint, it's safe to use higher values,
###. for inpainting and complex images is better to use lower values around 0.5

pipeline_img2img = AutoPipelineForImage2Image.from_pipe(pipeline, controlnet=None)

prompt = "Extend forms. Keep text in the image the same."
negative_prompt = ""

def lerp(a, b, t):
    return (1 - t) * a + t * b

# 5: https://chatgpt.com/share/6a3d6202-4ab8-83eb-8f06-6f7f535e958f
# 5: Generate the starting noise yourself
latent_shape = (
    1,
    pipeline.unet.config.in_channels,
    1024 // 8,
    1024 // 8,
) # 5

seed1 = 1234
seed2 = 5678

noise1 = torch.randn(
    latent_shape,
    generator=torch.Generator("cuda").manual_seed(seed1),
    device="cuda",
    dtype=torch.float16,
) # 5

noise2 = torch.randn(
    latent_shape,
    generator=torch.Generator("cuda").manual_seed(seed2),
    device="cuda",
    dtype=torch.float16,
) # 5


frames = []

seed = random.randint(0, 2**32 - 1)
generator = torch.Generator(device="cpu").manual_seed(seed)

num_frames = 60

for i in range(3):
    t = i / (num_frames - 1)

    # 5: Now Interpolate
    latents = lerp(noise1, noise2, t)

    image = pipeline(
        prompt=prompt,
        negative_prompt=negative_prompt,
        height=1024,
        width=1024,
        image=new_controlnet_image,
        controlnet_conditioning_scale=0.99,
        control_guidance_end=0.99,
        guidance_scale=3.0, # higher for stronger prompt reference
        num_inference_steps=25,
        # generator=generator,
        latents=latents,
        strength=0.9, # higher = model more freedom to incorporate the reference image
        ip_adapter_image=ip_mask,
        cross_attention_kwargs={"ip_adapter_masks": ip_masks},
    ).images[0]

    frames.append(image)

from PIL import Image

# frames = [PIL.Image, PIL.Image, ...]

gifName = "biscuit_43.gif"

frames[0].save(
    gifName,
    save_all=True,
    append_images=frames[1:],
    duration=250,  # milliseconds per frame
    loop=0,        # 0 = infinite loop
)

from IPython.display import Image as IImage
IImage(gifName, width=300)