# -*- coding: utf-8 -*-
"""Moving-Frog-Rotoscope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqZbMHn2emv4_axiG5UpcMCSO2HH8EP_
"""

# After trying to create a latent walk from the following references
# 1. Outpainting I - Controlnet version. Url: https://huggingface.co/blog/OzzyGT/outpainting-controlnet
# 2. A walk through latent space with Stable Diffusion. Url: https://keras.io/examples/generative/random_walks_with_stable_diffusion/

# I created a 'latent' walk based on code from ChatGPT
# 3. ChatGPT log Url: https://chatgpt.com/share/6a31c842-dec4-83eb-9b89-150aed089c89
# 4: ChatGPT https://chatgpt.com/share/6a17139b-3688-83eb-be26-68790e67b334

# Commented out IPython magic to ensure Python compatibility.
# Correct directory path for project
### cd error: https://chatgpt.com/share/6a31a9ad-4c68-83ed-939b-93ad436f48b8
# %cd /content/drive/MyDrive/2026/EMI/rotoscope

# Import necessary libraries
# 1:
import random
from io import BytesIO

import requests
import torch
from PIL import Image

from diffusers import (
    AutoPipelineForImage2Image,
    ControlNetModel,
    DPMSolverMultistepScheduler,
    StableDiffusionXLControlNetPipeline,
)
from diffusers.image_processor import IPAdapterMaskProcessor
from diffusers.utils import load_image, logging
from diffusers.utils.logging import set_verbosity

# 1: Controlnet Model
### 1: "controlnet for SDXL trained for inpainting by destitech"
controlnet = ControlNetModel.from_pretrained(
    "destitech/controlnet-inpaint-dreamer-sdxl", torch_dtype=torch.float16, variant="fp16"
)

# 4: Previously used code from a different project
input_folder = '/content/drive/MyDrive/2026/EMI/rotoscope/frames'

# 1:
pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
    "RunDiffusion/Juggernaut-XL-v9",
    torch_dtype=torch.float16,
    variant="fp16",
    controlnet=controlnet,
).to("cuda")

### 1: "[Controlnet Model is] easy to use, you just need to paint white the parts you want to replace"
### 1: "what I'm going to do is paint white the transparent part of the image.""

frames = [] # 3:

for i in range(1,5):
    num_str = str(i).zfill(1)

    # 1: To paint white the alpha channel of an image I use this code"
    ### Fetches an image with an edited transparent area illustrating what needs to be inpainted
    response = Image.open(f'{input_folder}/frame-{num_str}.png') # modified from 1
    control_image = response # modified from 1
    new_controlnet_image = Image.new("RGBA", control_image.size, "WHITE") # 1
    new_controlnet_image.alpha_composite(control_image) # 1

    ### 1: "This image has a 720x720 px size, SDXL works better with 1024x1024 images,
    ###     so the generations will be upscaled
    ###     you can use the smaller image but you'll probably get a lower quality image."

    ### "The conditional scale affects how much of the original image will be preserved,
    ###  since this is an outpaint, it's safe to use higher values,
    ###. for inpainting and complex images is better to use lower values around 0.5

    # 1: Prompts
    prompt = "Frog swimming in a pond"
    negative_prompt = ""

    # 1:
    seed = random.randint(0, 2**32 - 1)
    generator = torch.Generator(device="cpu").manual_seed(seed)

    # Changed to use one latent
    g1 = torch.Generator("cpu").manual_seed(seed)

    latent1 = pipeline(
        prompt=prompt,
        negative_prompt=negative_prompt,
        height=1024,
        width=1024,
        guidance_scale=6.5,
        num_inference_steps=25,
        image=new_controlnet_image,
        controlnet_conditioning_scale=0.9,
        control_guidance_end=0.9,
        generator=g1,
        output_type="latent",
    ).images[0]

    image = pipeline(
        prompt=prompt,
        negative_prompt=negative_prompt,
        height=1024,
        width=1024,
        guidance_scale=6.5,
        num_inference_steps=25,
        generator=generator,
        image=new_controlnet_image,
        controlnet_conditioning_scale=0.9,
        control_guidance_end=0.9,
    ).images[0]

    frames.append(image) # 3:

from PIL import Image

# frames = [PIL.Image, PIL.Image, ...]

frames[0].save(
    "latent_walk-2.gif",
    save_all=True,
    append_images=frames[1:],
    duration=250,  # milliseconds per frame
    loop=0,        # 0 = infinite loop
)

from IPython.display import Image as IImage
IImage("latent_walk-2.gif", width=300)

