# -*- coding: utf-8 -*-
"""Outpaint-Walk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2Bh71RU6QhV0sCU2kUSwEDoly1dYj7F
"""

####################
######## TO DO: Change and Include for GitHub Final Submission
####################

# Trying to add a diffusion walk
# I'm not sure this will work from the Keras example as they use the Keras Stable Diffsuion API
# I will rather try to use the Keras stable diffusion in this project

# Reference
# 1. Outpainting I - Controlnet version. Url: https://huggingface.co/blog/OzzyGT/outpainting-controlnet
# 2. A walk through latent space with Stable Diffusion. Url: https://keras.io/examples/generative/random_walks_with_stable_diffusion/

# Commented out IPython magic to ensure Python compatibility.
# Correct directory path for project
### cd error: https://chatgpt.com/share/6a31a9ad-4c68-83ed-939b-93ad436f48b8
# %cd /content/drive/MyDrive/2026/EMI/outpaint-hug

# Install Keras
# 2:
!pip install keras-cv --upgrade --quiet

# Add Keras & Keras Stable Diffusion Model
# 2:
import keras_cv
import keras
import matplotlib.pyplot as plt
from keras import ops
import numpy as np
import math
from PIL import Image

# Enable mixed precision
# (only do this if you have a recent NVIDIA GPU)
keras.mixed_precision.set_global_policy("mixed_float16")

# Instantiate the Stable Diffusion model
model = keras_cv.models.StableDiffusion(jit_compile=True)

# 2: Interpolating between text prompts

prompt_1 = "A watercolor painting of a Golden Retriever at the beach"
prompt_2 = "A still life DSLR photo of a bowl of fruit"
interpolation_steps = 5

encoding_1 = ops.squeeze(model.encode_text(prompt_1))
encoding_2 = ops.squeeze(model.encode_text(prompt_2))

interpolated_encodings = ops.linspace(encoding_1, encoding_2, interpolation_steps)

# Show the size of the latent manifold
print(f"Encoding shape: {encoding_1.shape}")

#2: "Once we've interpolated the encodings, we can generate images from each point"
seed = 12345
noise = keras.random.normal((512 // 8, 512 // 8, 4), seed=seed)

images = model.generate_image(
    interpolated_encodings,
    batch_size=interpolation_steps,
    diffusion_noise=noise,
)

# 2: Export as Gif

def export_as_gif(filename, images, frames_per_second=10, rubber_band=False):
    if rubber_band:
        images += images[2:-1][::-1]
    images[0].save(
        filename,
        save_all=True,
        append_images=images[1:],
        duration=1000 // frames_per_second,
        loop=0,
    )


export_as_gif(
    "doggo-and-fruit-5.gif",
    [Image.fromarray(img) for img in images],
    frames_per_second=2,
    rubber_band=True,
)

# 2: If you're running in Colab, you can view your own GIFs by running

from IPython.display import Image as IImage
IImage("doggo-and-fruit-5.gif")

#1: "this method only works when you can paint a white mask around the area you want to expand
#1: "With this method it is not necessary to prepare the area beforehand
#    but it has the limit that the image can only be as big as your VRAM allows it."

# Import necessary libraries
# 1:
import random
from io import BytesIO

import requests
import torch
from PIL import Image

from diffusers import (
    AutoPipelineForImage2Image,
    ControlNetModel,
    DPMSolverMultistepScheduler,
    StableDiffusionXLControlNetPipeline,
)
from diffusers.image_processor import IPAdapterMaskProcessor
from diffusers.utils import load_image, logging
from diffusers.utils.logging import set_verbosity

# 1: Controlnet Model
### 1: "controlnet for SDXL trained for inpainting by destitech"
controlnet = ControlNetModel.from_pretrained(
    "destitech/controlnet-inpaint-dreamer-sdxl", torch_dtype=torch.float16, variant="fp16"
)

### 1: "[Controlnet Model is] easy to use, you just need to paint white the parts you want to replace"
### 1: "what I'm going to do is paint white the transparent part of the image.""

# 1: To paint white the alpha channel of an image I use this code"
### Fetches an image with an edited transparent area illustrating what needs to be inpainted
response = requests.get("https://huggingface.co/datasets/OzzyGT/testing-resources/resolve/main/outpainting/313891870-adb6dc80-2e9e-420c-bac3-f93e6de8d06b.png?download=true")

control_image = Image.open(BytesIO(response.content))
new_controlnet_image = Image.new("RGBA", control_image.size, "WHITE")
new_controlnet_image.alpha_composite(control_image)

### 1: "This image has a 720x720 px size, SDXL works better with 1024x1024 images,
###     so the generations will be upscaled
###     you can use the smaller image but you'll probably get a lower quality image."

### "The conditional scale affects how much of the original image will be preserved,
###  since this is an outpaint, it's safe to use higher values,
###. for inpainting and complex images is better to use lower values around 0.5

# Prompts
prompt = "high quality photo of a wolf playing basketball, highly detailed, professional, dramatic ambient light, cinematic, dynamic background, focus"
negative_prompt = ""

seed = random.randint(0, 2**32 - 1)
generator = torch.Generator(device="cpu").manual_seed(seed)

pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
    "RunDiffusion/Juggernaut-XL-v9",
    torch_dtype=torch.float16,
    variant="fp16",
    controlnet=controlnet,
).to("cuda")

image = pipeline(
    prompt=prompt,
    negative_prompt=negative_prompt,
    height=1024,
    width=1024,
    guidance_scale=6.5,
    num_inference_steps=25,
    generator=generator,
    image=new_controlnet_image,
    controlnet_conditioning_scale=0.9,
    control_guidance_end=0.9,
).images[0]

image.save("result.png")

import IPython.display

IPython.display.Image('result.png')